language: java

notifications:
  email: false

services:
  - docker

before_script:
  - openssl aes-256-cbc -K $encrypted_703101643d9d_key -iv $encrypted_703101643d9d_iv -in travis_rsa.enc -out travis_rsa -d
  - ./.travis/configure.sh

script:
  - ./gradlew test build cli:fJ

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/5.1.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    - $HOME/runtime-js/.gradle/nodejs

jdk:
  - openjdk8

before_deploy:
  - .travis/prepare_deployment.sh

deploy:
  - provider: releases
    api_key:
      secure: Akty5JoTylVDZpKnvL/+uZaBVakrbmNbIQ4Dfp/PSR4zyZdphTbjVQPmrj9L823zScY6D4qocpGBHVRZoiaNpPQc0B7sWs6QxH7J+vW8glvy2rG416Flr1UZBp6r0IyPuUfZ37wHzd5jYfFIheVrbHoGHbtX4NYSZ323o3NvC48KpT3R68KUHISAbfOh26T81XGpWD3CpwNqHc9y5SAaE2aIHkCia2ySvxAEc7FW4g1iU2bt7sSA0JXRcFB1LWshZBxTNo3YzZLwPH7+oM4yKzS5M+poraOdrCffSMKJjCv2ACFie482iYy+3J4EHAx/rbSb4ru9D7UqQHTYIiByalYAVMahUifNDNlBPUyjcrLFJM0KxylGEvumpsABzqWjluOPxOjyZJ+rcqjQzC4Z7ifIRTpVJRq5Bv87H4JhIF8wqYxSeAHWUbQIwsOhr1WOOGYkCselV+sILLHupduWM892Wk+igwYCuVerNiIR1FNJ1yBIr5d9SNj660XMVHPEQ/hZqVCTTEPNcblS9vSHC5+LaQn5SAmOmgLgzSJHjlMTYczALdz8IeadAQgdq01RXbRjf6ni/l/T0m7cbxMzEtK9hLLAhRNg5lik99BI/hAXN9MvcFi1yEVHo0iFMeI0k8k86PVv4vPatmjz9zzXskD+hDy46cP663cm3pGw3sI=
    file_glob: true
    file: publish/**
    skip_cleanup: true
    on:
      branch: master
      repo: rewe-digital-incubator/Konversation
      tags: true
      condition: $TRAVIS_TAG =~ ^cli-
  - provider: script
    script: .travis/deploy_chocolaty.sh
    on:
      branch: master
      repo: rewe-digital-incubator/Konversation
      tags: true
      condition: $TRAVIS_TAG =~ ^cli-
  - provider: script
    script: gradlew runtime-js:publishNpmPackage
    on:
      branch: master
      repo: rewe-digital-incubator/Konversation
      tags: true
      condition: $TRAVIS_TAG =~ ^js-
  - provider: script
    script: gradlew runtime-jvm:bintrayUpload
    on:
      branch: master
      repo: rewe-digital-incubator/Konversation
      tags: true
      condition: $TRAVIS_TAG =~ ^jvm-
  - provider: script
    script: gradlew gradle-plugin:publishPlugins
    on:
      branch: master
      repo: rewe-digital-incubator/Konversation
      tags: true
      condition: $TRAVIS_TAG =~ ^gradle-